import type { Lang } from './i18n'

// 화면 문구.
//
// 번역투를 피한다 — 한국어를 그대로 옮기지 않고 각 언어에서 자연스러운 말로 쓴다.
// 예: '내 여행지 주변 축제'를 영어로 직역하면 어색하므로 'What's on near you'로 간다.

type Dict = Record<string, string>

const ko: Dict = {
  'brand.tagline': '내 여행지 주변 축제',
  'home.headline': '지금, 어디로 가시나요?',
  'home.sub': '전국 {n}개 축제를 날짜와 위치로 찾아드립니다.',
  'search.placeholder': '축제·지역 검색 (예: 강릉, 불꽃축제)',
  'search.button': '검색',
  'nearby.title': '내 주변에서 열리는 축제',
  'nearby.asking': '위치를 확인하는 중…',
  'nearby.denied': '위치를 켜면 지금 계신 곳 기준으로 가까운 축제를 보여드려요.',
  'nearby.retry': '위치 허용하기',
  'nearby.found': '반경 {r}km 안에 {n}곳',
  'nearby.none': '반경 {r}km 안에는 지금 열리는 축제가 없어요',
  'nearby.seeAll': '가까운 순으로 모두 보기',
  'purpose.title': '무엇을 하러 가시나요?',
  'purpose.sub': '목적을 고르면 그에 맞는 축제만 모아 보여드려요.',
  'popular.title': '지금 사람들이 많이 찾는 축제',
  'region.title': '지역으로 찾기',
  'month.title': '언제 가시나요?',
  'status.ongoing': '진행중',
  'status.upcoming': '예정',
  'status.always': '상시',
  'badge.endsToday': '오늘 종료',
  'badge.dday': 'D-{n}',
  'region.sub': '권역을 고르면 그 지역 축제만 모아 보여드려요.',
  'detail.contents': '목차',
  'review.title': '방문 후기',
  'review.count': '({n}건)',
  'review.moderated': '남겨주신 후기는 검토 후 공개돼요. 하루 안에 올라갑니다.',
  'report.open': '정보가 틀렸나요? 알려주세요',
  'report.title': '어떤 정보가 틀렸나요?',
  'report.note': '알려주시면 확인하고 고칠게요. 로그인은 안 하셔도 돼요.',
  'report.kind.dates': '날짜',
  'report.kind.place': '장소',
  'report.kind.canceled': '취소·중단됨',
  'report.kind.photo': '사진',
  'report.kind.link': '홈페이지 링크',
  'report.kind.other': '그 밖에',
  'report.placeholder': '무엇이 어떻게 다른지 알려주세요. 예: 올해는 9월 12일부터예요.',
  'report.contact': '답을 받고 싶으시면 이메일 (선택)',
  'report.submit': '보내기',
  'report.cancel': '취소',
  'report.needBody': '무엇이 틀렸는지 적어주세요.',
  'report.thanks': '고맙습니다. 확인하고 고칠게요.',
  'map.open': '카카오맵에서 길찾기',
  'share.copy': '링크 복사',
  'share.kakao': '카카오톡으로 공유',
  'share.more': '다른 앱으로 공유',
  'login.kakao': '카카오로 계속하기',
  'login.google': 'Google로 계속하기',
  'login.or': '또는 이메일로',
  'review.signOut': '로그아웃',
  'review.loginTitle': '후기를 남기려면 이메일로 로그인해 주세요',
  'review.loginNote': '비밀번호가 없어요. 메일로 온 링크를 누르면 로그인됩니다.',
  'review.sendLink': '로그인 링크 받기',
  'review.linkSent': '메일함을 확인해 주세요. 링크를 누르면 이 화면으로 돌아옵니다.',
  'review.placeholder': '무엇이 좋았나요? 언제 가면 좋을지, 뭘 챙겨가면 좋을지 알려주시면 다음 사람에게 큰 도움이 돼요.',
  'review.submit': '후기 남기기',
  'review.thanks': '고맙습니다. 검토 후 공개할게요.',
  'review.empty': '아직 후기가 없어요. 다녀오셨다면 첫 후기를 남겨주세요.',
  'review.needRating': '별점을 골라주세요.',
  'review.needBody': '열 글자 이상 적어주세요.',
  'review.needLogin': '로그인이 풀렸어요. 다시 로그인해 주세요.',
  'review.helpful': '{n}명에게 도움이 됐어요',

  'status.selectDates': '기간 중 일부 날짜',
  'poster.past': '지난 회차 포스터',
  'photo.pending': '포스터 준비 중',
  'grade.mf': '문화관광축제',
  'graded.title': '나라가 고른 축제만 모아 봤어요',
  'graded.sub': '문화체육관광부가 심사해 지정한 {n}곳이에요. 지정 축제는 방문객이 평소의 1.3배까지 늘었어요.',
  'graded.cta': '지정 축제 보기',
  'promo.title': '이번 주말, KOTA’s Pick',
  'promo.sub': '토·일에 열리는 {n}곳 중에서 골랐어요. 지난 회차에 사람이 많이 몰렸고 사진으로 분위기를 볼 수 있는 축제예요.',
  'promo.pause': '자동 넘김 멈추기',
  'promo.play': '자동 넘김 다시 시작',
  'promo.subCurated': '이번 주에 가볼 만한 곳을 직접 골랐어요.',
  'promo.cta': '이번 주말 축제 모두 보기',
  'row.ending': '곧 끝나요',
  'row.ending.sub': '이번 주 안에 끝나는 축제',
  'row.weekend': '이번 주말',
  'row.weekend.sub': '토·일에 열려요',
  'row.next': '다음 달에 열려요',
  'row.next.sub': '미리 계획하기 좋은 축제',
  'row.more': '모두 보기',
  'detail.about': '소개',
  'detail.photos': '사진',
  'detail.photos.src': '사진 © 한국관광공사 TourAPI (공공누리 제3유형: 출처표시·변경금지)',
  'detail.food': '먹거리',
  'detail.program': '프로그램',
  'detail.video': '영상',
  'detail.location': '위치',
  'detail.info': '기본 정보',
  'detail.organizer': '주최',
  'detail.hours': '운영 시간',
  'detail.age': '관람 연령',
  'detail.more': '더보기',
  'detail.less': '접기',
  'detail.share': '공유',
  'detail.copied': '링크를 복사했어요',
  'detail.source': '출처: 한국관광공사·문화체육관광부·지자체 공공데이터. 현장 사정에 따라 바뀔 수 있어요.',
  'detail.booth.n': '{n}개 부스',
  'detail.booth.past': '지난 회차 기준 — 올해 메뉴·가격은 바뀔 수 있어요',
  'detail.menu.n': '메뉴 {n}개',
  'detail.won': '{n}원',
  'crumb.home': '홈',
  'lift.label': '지난 회차 개최지 방문객 {x}배',
  'rank.region': '{sido} 축제 {total}곳 중 방문객 {rank}위',
  'rank.note': '지난 회차 방문객 실측 기준. 방문자 데이터가 있는 축제끼리 비교했어요.',
  'lift.note': '한국관광공사 관광빅데이터(통신사 방문자수) — 축제 기간 외지인 방문 피크 ÷ 전후 4주 같은 요일 평소',
  'list.total': '축제 {n}곳',
  'detail.period': '기간',
  'detail.fee': '요금',
  'detail.free': '무료',
  'nav.festivals': '전국 축제',
  'detail.place': '장소',
  'detail.tel': '문의',
  'detail.homepage': '홈페이지',
  'official.title': '공식 홈페이지',
  'official.sub': '일정 변경·예매·상세 프로그램은 주최측 공지가 가장 정확해요',
  'official.visit': '공식 홈페이지 열기',
  'official.insta': '인스타그램',
  'official.tel': '전화 문의',
  'img.src': '이미지 출처',
  'detail.directions': '길찾기',
  'detail.back': '목록으로',
  'detail.nearby': '이 근처 다른 축제',
  'foot.disclaimer': '축제 일정·장소는 주최 측 사정으로 바뀔 수 있습니다. 방문 전 공식 채널로 확인해 주세요.',
  'foot.source': '데이터: 한국관광공사 TourAPI · 공공데이터포털 · 각 지자체',
}

const en: Dict = {
  'brand.tagline': "What's on near you",
  'home.headline': 'Where are you headed?',
  'home.sub': 'Find {n} festivals across Korea by date and location.',
  'search.placeholder': 'Search a festival or place (e.g. Gangneung, fireworks)',
  'search.button': 'Search',
  'nearby.title': 'Festivals near you',
  'nearby.asking': 'Finding your location…',
  'nearby.denied': 'Turn on location and we’ll show what’s on around you.',
  'nearby.retry': 'Allow location',
  'nearby.found': '{n} within {r} km',
  'nearby.none': 'Nothing on within {r} km right now',
  'nearby.seeAll': 'See all by distance',
  'purpose.title': 'What are you in the mood for?',
  'purpose.sub': 'Pick a purpose and we’ll narrow it down.',
  'popular.title': 'Popular right now',
  'region.title': 'Browse by region',
  'month.title': 'When are you going?',
  'status.ongoing': 'On now',
  'status.upcoming': 'Upcoming',
  'status.always': 'Year-round',
  'badge.endsToday': 'Ends today',
  'badge.dday': 'D-{n}',
  'region.sub': 'Pick a region to see only its festivals.',
  'detail.contents': 'Contents',
  'review.title': 'Reviews',
  'review.count': '({n} reviews)',
  'review.moderated': 'Reviews are published after a quick check, usually within a day.',
  'report.open': 'Something wrong? Tell us',
  'report.title': 'What looks wrong?',
  'report.note': 'We will check and fix it. No sign-in needed.',
  'report.kind.dates': 'Dates',
  'report.kind.place': 'Place',
  'report.kind.canceled': 'Cancelled',
  'report.kind.photo': 'Photo',
  'report.kind.link': 'Website link',
  'report.kind.other': 'Something else',
  'report.placeholder': 'Tell us what differs. e.g. This year it starts on 12 September.',
  'report.contact': 'Email, if you want a reply (optional)',
  'report.submit': 'Send',
  'report.cancel': 'Cancel',
  'report.needBody': 'Please tell us what is wrong.',
  'report.thanks': 'Thank you. We will check and fix it.',
  'map.open': 'Open in KakaoMap',
  'share.copy': 'Copy link',
  'share.kakao': 'Share on KakaoTalk',
  'share.more': 'Share via…',
  'login.kakao': 'Continue with Kakao',
  'login.google': 'Continue with Google',
  'login.or': 'or with email',
  'review.signOut': 'Sign out',
  'review.loginTitle': 'Sign in with your email to leave a review',
  'review.loginNote': 'No password. Just tap the link we email you.',
  'review.sendLink': 'Email me a link',
  'review.linkSent': 'Check your inbox. The link brings you back here.',
  'review.placeholder': 'What was good? Tell us when to go and what to bring — it helps the next traveller.',
  'review.submit': 'Post review',
  'review.thanks': 'Thank you. We will publish it after a quick check.',
  'review.empty': 'No reviews yet. If you have been, be the first.',
  'review.needRating': 'Pick a rating.',
  'review.needBody': 'Please write at least 10 characters.',
  'review.needLogin': 'Your session expired. Please sign in again.',
  'review.helpful': '{n} found this helpful',

  'status.selectDates': 'Select dates only',
  'poster.past': 'Poster from a past edition',
  'photo.pending': 'Poster coming soon',
  'grade.mf': 'Designated Culture & Tourism Festival',
  'graded.title': 'Festivals picked by the government',
  'graded.sub': '{n} festivals vetted by the Ministry of Culture, Sports and Tourism. Designated ones drew up to 1.3× more visitors.',
  'graded.cta': 'See designated festivals',
  'promo.title': 'This weekend — KOTA’s Pick',
  'promo.sub': 'Chosen from {n} festivals running this Saturday and Sunday — the ones that drew crowds last time and show you what to expect.',
  'promo.pause': 'Pause autoplay',
  'promo.play': 'Resume autoplay',
  'promo.subCurated': 'Hand-picked places worth your weekend.',
  'promo.cta': 'See all weekend festivals',
  'row.ending': 'Ending soon',
  'row.ending.sub': 'Wraps up within the week',
  'row.weekend': 'This weekend',
  'row.weekend.sub': 'Open Saturday and Sunday',
  'row.next': 'Coming next month',
  'row.next.sub': 'Worth planning a trip around',
  'row.more': 'See all',
  'detail.about': 'About',
  'detail.photos': 'Photos',
  'detail.photos.src': 'Photos © Korea Tourism Organization TourAPI (KOGL Type 3: attribution, no derivatives)',
  'detail.food': 'Food & drink',
  'detail.program': 'Program',
  'detail.video': 'Video',
  'detail.location': 'Location',
  'detail.info': 'Essentials',
  'detail.organizer': 'Organizer',
  'detail.hours': 'Hours',
  'detail.age': 'Ages',
  'detail.more': 'Read more',
  'detail.less': 'Show less',
  'detail.share': 'Share',
  'detail.copied': 'Link copied',
  'detail.source': 'Source: Korea Tourism Organization, Ministry of Culture, and local governments (open data). Details may change on site.',
  'detail.booth.n': '{n} stalls',
  'detail.booth.past': 'From last edition — this year\'s menu and prices may differ',
  'detail.menu.n': '{n} items',
  'detail.won': '₩{n}',
  'crumb.home': 'Home',
  'lift.label': '{x}× visitors at last edition',
  'rank.region': 'No. {rank} of {total} festivals in {sido} by visitors',
  'rank.note': 'Based on measured visitors at the last edition, among festivals with visitor data.',
  'lift.note': 'Korea Tourism Organization big data (mobile-carrier visitor counts) — peak out-of-town visitors during the festival ÷ same weekday, 4 weeks around',
  'list.total': '{n} festivals',
  'detail.period': 'Dates',
  'detail.fee': 'Admission',
  'detail.free': 'Free',
  'nav.festivals': 'All festivals',
  'detail.place': 'Where',
  'detail.tel': 'Contact',
  'detail.homepage': 'Website',
  'official.title': 'Official website',
  'official.sub': 'The organizer\'s own notices are the most reliable for schedule changes, tickets, and program details',
  'official.visit': 'Open official website',
  'official.insta': 'Instagram',
  'official.tel': 'Call',
  'img.src': 'Image source',
  'detail.directions': 'Directions',
  'detail.back': 'Back to list',
  'detail.nearby': 'Other festivals nearby',
  'foot.disclaimer': 'Dates and venues can change. Please check the official channel before you go.',
  'foot.source': 'Data: Korea Tourism Organization TourAPI · data.go.kr · local governments',
}

const ja: Dict = {
  'brand.tagline': '旅先の近くで開かれる祭り',
  'home.headline': '今日は、どこへ？',
  'home.sub': '韓国全土の祭り{n}件を、日付と現在地から探せます。',
  'search.placeholder': '祭り・地域を検索（例：江陵、花火）',
  'search.button': '検索',
  'nearby.title': '近くで開催中の祭り',
  'nearby.asking': '現在地を確認しています…',
  'nearby.denied': '位置情報を許可すると、今いる場所の近くの祭りをお見せします。',
  'nearby.retry': '位置情報を許可',
  'nearby.found': '半径{r}kmに{n}件',
  'nearby.none': '半径{r}km以内で開催中の祭りはありません',
  'nearby.seeAll': '近い順にすべて見る',
  'purpose.title': '何をしに行きますか？',
  'purpose.sub': '目的を選ぶと、それに合う祭りだけを集めます。',
  'popular.title': '今よく見られている祭り',
  'region.title': '地域から探す',
  'month.title': 'いつ行きますか？',
  'status.ongoing': '開催中',
  'status.upcoming': '開催予定',
  'status.always': '通年',
  'badge.endsToday': '本日終了',
  'badge.dday': 'D-{n}',
  'region.sub': '地域を選ぶとその地域の祭りだけをまとめて表示します。',
  'detail.contents': '目次',
  'review.title': '訪問レビュー',
  'review.count': '({n}件)',
  'review.moderated': 'いただいたレビューは確認後に公開されます（通常1日以内）。',
  'report.open': '情報が違いますか？お知らせください',
  'report.title': 'どの情報が違いますか？',
  'report.note': '確認して直します。ログインは不要です。',
  'report.kind.dates': '日程',
  'report.kind.place': '場所',
  'report.kind.canceled': '中止・終了',
  'report.kind.photo': '写真',
  'report.kind.link': '公式サイトのリンク',
  'report.kind.other': 'その他',
  'report.placeholder': '何がどう違うか教えてください。例：今年は9月12日からです。',
  'report.contact': '返信をご希望ならメール（任意）',
  'report.submit': '送信',
  'report.cancel': 'キャンセル',
  'report.needBody': '何が違うのかご記入ください。',
  'report.thanks': 'ありがとうございます。確認して直します。',
  'map.open': 'カカオマップで道案内',
  'share.copy': 'リンクをコピー',
  'share.kakao': 'カカオトークで共有',
  'share.more': '他のアプリで共有',
  'login.kakao': 'カカオで続ける',
  'login.google': 'Googleで続ける',
  'login.or': 'またはメールで',
  'review.signOut': 'ログアウト',
  'review.loginTitle': 'レビューを書くにはメールでログインしてください',
  'review.loginNote': 'パスワードは不要です。届いたリンクを押すとログインできます。',
  'review.sendLink': 'ログインリンクを受け取る',
  'review.linkSent': 'メールをご確認ください。リンクからこの画面に戻れます。',
  'review.placeholder': '何が良かったですか？いつ行くとよいか、何を持っていくとよいかを教えていただけると次の方の助けになります。',
  'review.submit': 'レビューを投稿',
  'review.thanks': 'ありがとうございます。確認後に公開します。',
  'review.empty': 'まだレビューがありません。行かれた方はぜひ最初の一件を。',
  'review.needRating': '評価を選んでください。',
  'review.needBody': '10文字以上でお書きください。',
  'review.needLogin': 'ログインが切れました。もう一度ログインしてください。',
  'review.helpful': '{n}人の役に立ちました',

  'status.selectDates': '期間中の特定日',
  'poster.past': '過去開催のポスター',
  'photo.pending': 'ポスター準備中',
  'grade.mf': '文化観光祭り指定',
  'graded.title': '国が選んだ祭りだけを集めました',
  'graded.sub': '文化体育観光部が審査して指定した{n}件です。指定された祭りは来訪者が普段の1.3倍まで増えました。',
  'graded.cta': '指定された祭りを見る',
  'promo.title': '今週末の KOTA’s Pick',
  'promo.sub': '土日に開かれる{n}件から選びました。前回よく賑わい、写真で雰囲気がわかる祭りです。',
  'promo.pause': '自動送りを止める',
  'promo.play': '自動送りを再開',
  'promo.subCurated': '今週行ってみる価値のある場所を選びました。',
  'promo.cta': '今週末の祭りをすべて見る',
  'row.ending': 'まもなく終了',
  'row.ending.sub': '今週中に終わる祭り',
  'row.weekend': '今週末',
  'row.weekend.sub': '土日に開催',
  'row.next': '来月の祭り',
  'row.next.sub': '旅の計画を立てるなら',
  'row.more': 'すべて見る',
  'detail.about': '概要',
  'detail.photos': '写真',
  'detail.photos.src': '写真 © 韓国観光公社 TourAPI（KOGL第3類型：出典表示・変更禁止）',
  'detail.food': 'グルメ',
  'detail.program': 'プログラム',
  'detail.video': '動画',
  'detail.location': '場所',
  'detail.info': '基本情報',
  'detail.organizer': '主催',
  'detail.hours': '時間',
  'detail.age': '対象年齢',
  'detail.more': 'もっと見る',
  'detail.less': '閉じる',
  'detail.share': '共有',
  'detail.copied': 'リンクをコピーしました',
  'detail.source': '出典：韓国観光公社・文化体育観光部・自治体の公共データ。現地の事情で変わることがあります。',
  'detail.booth.n': '{n}ブース',
  'detail.booth.past': '前回開催時の情報 — 今年のメニュー・価格は変わることがあります',
  'detail.menu.n': '{n}品',
  'detail.won': '{n}ウォン',
  'crumb.home': 'ホーム',
  'lift.label': '前回開催時 来訪者{x}倍',
  'rank.region': '{sido}の祭り{total}件中 来訪者{rank}位',
  'rank.note': '前回開催時の実測来訪者数による順位。来訪データのある祭り同士の比較です。',
  'lift.note': '韓国観光公社ビッグデータ（通信キャリア来訪者数）— 祭り期間の域外来訪ピーク ÷ 前後4週の同曜日',
  'list.total': '祭り{n}件',
  'detail.period': '期間',
  'detail.fee': '料金',
  'detail.free': '無料',
  'nav.festivals': '全国の祭り',
  'detail.place': '会場',
  'detail.tel': 'お問い合わせ',
  'detail.homepage': '公式サイト',
  'official.title': '公式サイト',
  'official.sub': '日程変更・チケット・詳細プログラムは主催者の告知が最も正確です',
  'official.visit': '公式サイトを開く',
  'official.insta': 'Instagram',
  'official.tel': '電話で問い合わせ',
  'img.src': '画像の出典',
  'detail.directions': '経路',
  'detail.back': '一覧へ戻る',
  'detail.nearby': 'この近くの祭り',
  'foot.disclaimer': '日程・会場は主催者の都合で変更される場合があります。お出かけ前に公式情報をご確認ください。',
  'foot.source': 'データ：韓国観光公社 TourAPI・公共データポータル・各自治体',
}

const th: Dict = {
  'brand.tagline': 'เทศกาลใกล้จุดหมายของคุณ',
  'home.headline': 'วันนี้จะไปไหนดี?',
  'home.sub': 'ค้นหาเทศกาล {n} งานทั่วเกาหลี ตามวันที่และตำแหน่งของคุณ',
  'search.placeholder': 'ค้นหาเทศกาลหรือพื้นที่ (เช่น คังนึง, พลุ)',
  'search.button': 'ค้นหา',
  'nearby.title': 'เทศกาลใกล้คุณ',
  'nearby.asking': 'กำลังตรวจสอบตำแหน่ง…',
  'nearby.denied': 'เปิดตำแหน่งแล้วเราจะแสดงเทศกาลรอบตัวคุณ',
  'nearby.retry': 'อนุญาตตำแหน่ง',
  'nearby.found': '{n} งานในรัศมี {r} กม.',
  'nearby.none': 'ไม่มีเทศกาลที่กำลังจัดในรัศมี {r} กม.',
  'nearby.seeAll': 'ดูทั้งหมดตามระยะทาง',
  'purpose.title': 'อยากไปทำอะไร?',
  'purpose.sub': 'เลือกจุดประสงค์ แล้วเราจะคัดให้',
  'popular.title': 'กำลังได้รับความนิยม',
  'region.title': 'ค้นหาตามภูมิภาค',
  'month.title': 'จะไปเมื่อไหร่?',
  'status.ongoing': 'กำลังจัด',
  'status.upcoming': 'กำลังจะจัด',
  'status.always': 'ตลอดปี',
  'badge.endsToday': 'สิ้นสุดวันนี้',
  'badge.dday': 'D-{n}',
  'region.sub': 'เลือกภูมิภาคเพื่อดูเฉพาะเทศกาลในพื้นที่นั้น',
  'detail.contents': 'สารบัญ',
  'review.title': 'รีวิวจากผู้มาเยือน',
  'review.count': '({n} รีวิว)',
  'review.moderated': 'รีวิวจะเผยแพร่หลังตรวจสอบ โดยปกติภายในหนึ่งวัน',
  'report.open': 'ข้อมูลผิดใช่ไหม? แจ้งเราได้',
  'report.title': 'ข้อมูลใดที่ไม่ถูกต้อง?',
  'report.note': 'เราจะตรวจสอบและแก้ไข ไม่ต้องเข้าสู่ระบบ',
  'report.kind.dates': 'วันที่',
  'report.kind.place': 'สถานที่',
  'report.kind.canceled': 'ยกเลิกแล้ว',
  'report.kind.photo': 'รูปภาพ',
  'report.kind.link': 'ลิงก์เว็บไซต์',
  'report.kind.other': 'อื่น ๆ',
  'report.placeholder': 'บอกเราว่าต่างอย่างไร เช่น ปีนี้เริ่ม 12 กันยายน',
  'report.contact': 'อีเมล หากต้องการคำตอบ (ไม่บังคับ)',
  'report.submit': 'ส่ง',
  'report.cancel': 'ยกเลิก',
  'report.needBody': 'กรุณาบอกว่าอะไรไม่ถูกต้อง',
  'report.thanks': 'ขอบคุณค่ะ เราจะตรวจสอบและแก้ไข',
  'map.open': 'เปิดใน KakaoMap',
  'share.copy': 'คัดลอกลิงก์',
  'share.kakao': 'แชร์ผ่าน KakaoTalk',
  'share.more': 'แชร์ผ่านแอปอื่น',
  'login.kakao': 'ดำเนินการต่อด้วย Kakao',
  'login.google': 'ดำเนินการต่อด้วย Google',
  'login.or': 'หรือด้วยอีเมล',
  'review.signOut': 'ออกจากระบบ',
  'review.loginTitle': 'เข้าสู่ระบบด้วยอีเมลเพื่อเขียนรีวิว',
  'review.loginNote': 'ไม่ต้องใช้รหัสผ่าน แค่กดลิงก์ที่ส่งไปทางอีเมล',
  'review.sendLink': 'ส่งลิงก์เข้าสู่ระบบ',
  'review.linkSent': 'กรุณาตรวจสอบอีเมล ลิงก์จะพากลับมาที่หน้านี้',
  'review.placeholder': 'อะไรที่ดี? บอกเราว่าควรไปเมื่อไหร่และควรเตรียมอะไร จะช่วยผู้เดินทางคนต่อไปได้มาก',
  'review.submit': 'โพสต์รีวิว',
  'review.thanks': 'ขอบคุณค่ะ เราจะเผยแพร่หลังตรวจสอบ',
  'review.empty': 'ยังไม่มีรีวิว หากคุณเคยไปมา มาเป็นคนแรกกันเถอะ',
  'review.needRating': 'กรุณาเลือกคะแนน',
  'review.needBody': 'กรุณาเขียนอย่างน้อย 10 ตัวอักษร',
  'review.needLogin': 'เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง',
  'review.helpful': '{n} คนเห็นว่ามีประโยชน์',

  'status.selectDates': 'เฉพาะบางวัน',
  'poster.past': 'โปสเตอร์ปีก่อน',
  'photo.pending': 'อยู่ระหว่างเตรียมโปสเตอร์',
  'grade.mf': 'เทศกาลวัฒนธรรมและการท่องเที่ยวที่ได้รับการรับรอง',
  'graded.title': 'เทศกาลที่รัฐบาลคัดเลือก',
  'graded.sub': '{n} เทศกาลที่กระทรวงวัฒนธรรมฯ คัดเลือก มีผู้มาเยือนเพิ่มขึ้นถึง 1.3 เท่า',
  'graded.cta': 'ดูเทศกาลที่ได้รับการรับรอง',
  'promo.title': 'สุดสัปดาห์นี้ — KOTA’s Pick',
  'promo.sub': 'คัดจาก {n} เทศกาลที่จัดในเสาร์-อาทิตย์นี้ เลือกจากที่คนไปเยอะครั้งก่อนและมีภาพให้ดูบรรยากาศ',
  'promo.pause': 'หยุดเลื่อนอัตโนมัติ',
  'promo.play': 'เล่นต่อ',
  'promo.subCurated': 'คัดสรรสถานที่น่าไปสำหรับสุดสัปดาห์นี้',
  'promo.cta': 'ดูเทศกาลสุดสัปดาห์ทั้งหมด',
  'row.ending': 'ใกล้จบแล้ว',
  'row.ending.sub': 'จบภายในสัปดาห์นี้',
  'row.weekend': 'สุดสัปดาห์นี้',
  'row.weekend.sub': 'เปิดวันเสาร์และอาทิตย์',
  'row.next': 'เดือนหน้า',
  'row.next.sub': 'เหมาะกับการวางแผนล่วงหน้า',
  'row.more': 'ดูทั้งหมด',
  'detail.about': 'เกี่ยวกับ',
  'detail.photos': 'รูปภาพ',
  'detail.photos.src': 'ภาพ © องค์การส่งเสริมการท่องเที่ยวเกาหลี TourAPI (KOGL ประเภท 3: ระบุที่มา ห้ามดัดแปลง)',
  'detail.food': 'อาหารและเครื่องดื่ม',
  'detail.program': 'โปรแกรม',
  'detail.video': 'วิดีโอ',
  'detail.location': 'ที่ตั้ง',
  'detail.info': 'ข้อมูลสำคัญ',
  'detail.organizer': 'ผู้จัด',
  'detail.hours': 'เวลา',
  'detail.age': 'ช่วงอายุ',
  'detail.more': 'อ่านเพิ่ม',
  'detail.less': 'ย่อ',
  'detail.share': 'แชร์',
  'detail.copied': 'คัดลอกลิงก์แล้ว',
  'detail.source': 'ที่มา: องค์การส่งเสริมการท่องเที่ยวเกาหลี กระทรวงวัฒนธรรม และท้องถิ่น (ข้อมูลเปิด) รายละเอียดอาจเปลี่ยนแปลงหน้างาน',
  'detail.booth.n': '{n} ร้าน',
  'detail.booth.past': 'ข้อมูลจากครั้งก่อน — เมนูและราคาปีนี้อาจเปลี่ยน',
  'detail.menu.n': '{n} รายการ',
  'detail.won': '{n} วอน',
  'crumb.home': 'หน้าแรก',
  'lift.label': 'ผู้มาเยือน {x} เท่าในครั้งก่อน',
  'rank.region': 'อันดับ {rank} จาก {total} เทศกาลใน{sido} ตามจำนวนผู้มาเยือน',
  'rank.note': 'อ้างอิงจำนวนผู้มาเยือนจริงครั้งก่อน เปรียบเทียบเฉพาะเทศกาลที่มีข้อมูล',
  'lift.note': 'ข้อมูลบิ๊กดาต้าการท่องเที่ยวเกาหลี (จำนวนผู้มาเยือนจากเครือข่ายมือถือ) — ยอดสูงสุดช่วงเทศกาล ÷ วันเดียวกันของสัปดาห์ 4 สัปดาห์โดยรอบ',
  'list.total': 'เทศกาล {n} งาน',
  'detail.period': 'ช่วงวันที่',
  'detail.fee': 'ค่าเข้า',
  'detail.free': 'ฟรี',
  'nav.festivals': 'เทศกาลทั้งหมด',
  'detail.place': 'สถานที่',
  'detail.tel': 'ติดต่อ',
  'detail.homepage': 'เว็บไซต์',
  'official.title': 'เว็บไซต์ทางการ',
  'official.sub': 'ประกาศจากผู้จัดงานแม่นยำที่สุดสำหรับการเปลี่ยนแปลงกำหนดการ บัตร และรายละเอียด',
  'official.visit': 'เปิดเว็บไซต์ทางการ',
  'official.insta': 'Instagram',
  'official.tel': 'โทรสอบถาม',
  'img.src': 'ที่มาของภาพ',
  'detail.directions': 'เส้นทาง',
  'detail.back': 'กลับไปที่รายการ',
  'detail.nearby': 'เทศกาลอื่นใกล้เคียง',
  'foot.disclaimer': 'วันและสถานที่อาจเปลี่ยนแปลงได้ กรุณาตรวจสอบกับผู้จัดก่อนเดินทาง',
  'foot.source': 'ข้อมูล: องค์การส่งเสริมการท่องเที่ยวเกาหลี TourAPI · data.go.kr · หน่วยงานท้องถิ่น',
}

const DICTS: Record<Lang, Dict> = { ko, en, ja, th }

/** 문구 조회. {n} 같은 자리표시자는 vars로 채운다 */
export function t(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  let s = DICTS[lang][key] ?? DICTS.ko[key] ?? key
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v))
  return s
}
